export const APIs = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/create",
  GET_USER: "/user",
  AVATAR: "/avatar",
  STORE: "/store",
  VERIFY: "/auth/verify",
  STRIPE_ORDER: "/stripe/order",
  STRIPE_PRICES: "/stripe/prices",
  CHANGE_PASSWORD: "/auth/create-new-password",
  GET_USER_PROFILE: "/user/profile",
  VERIFY_REGISTER: "/auth/verify-register",
  FORGET_PASSWORD: "/auth/forget-password",
  GENERATE_NEW_TOKEN: "/auth/generate-new-token",
  SAVE_IMAGE_AI: "/store/save-image",
  GET_USER_INFO: "/auth/user-info",
  USE_CREDITS: "/user/use-credits",
  GET_AVATAR_LIST: "/avatar/list",
  GET_AVATAR_LIST_BY_USER: "/avatar/list-by-user",
  GET_AVATAR_LIST_BY_STATUS: "/avatar/list-by-status",

  GENERATE_ENHANCE_AI: "https://enhance-core.apero.vn/api/v1/image-enhance",
  CREATE_IMAGE_AI: "https://api-img-gen-wrapper.apero.vn/api/v2/image-ai",
  REMOVE_BACKGROUND: "https://bgrm-enhance-wrapper.apero.vn/api/v1/bg-remove",
  GET_STYLES:
    "https://style-management-api.dev.apero.vn/v2/styles?limit=1000000&page=1&project=Creatorhub_WEB",
};
