export const ROUTES = {
  BASE_URL: "http://localhost:3000/",
  HOME: "/",
  SIGN_IN: "/sign-in",
  REGISTER: "/register",
  PRICING: "/pricing",
  HOME_PAGE: "/home-page",
  AI_IMAGE_RESULT: "/ai-image-result",
  AI_ART_GENERATOR: "/ai-art-generator",
  AI_PHOTO_ENHANCER: "/ai-photo-enhancer",
  AI_BACKGROUND_REMOVE: "/ai-background-remove",
  MY_ACCOUNT: "/my-account",
  CHANGE_PASSWORD: "/change-password",
  VERIFY_REGISTER: "/verify-register",
  ACCOUNT_MANAGEMENT: "/account-management",
  ERROR: "*",
};
